name: Pull Request
on: pull_request

jobs:
  add-label:
    permissions:
      contents: read
    uses: murn0/auto-add-labels-workflow/.github/workflows/main.yaml@f97918aeaeddccf4be0689d48f05b82403c21586 # v0.4.1
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}
  
  auto-merge:
    permissions:
      contents: read
    uses: ./.github/workflows/main.yaml
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - aqua/aqua.yaml
          - aqua/imports/ghalint.yaml
          - ghalint.yaml
        renovate-config-validator:
          - renovate.json
          - .github/workflows/main.yaml
          - .github/workflows/test.yaml
          - .github/workflows/pull_request.yaml
          - .github/workflows/wc-renovate-config-validator.yaml
        update-aqua-checksums:
          - aqua/aqua.yaml
          - aqua/imports/*.yaml
          - aqua/aqua-checksums.json
          - .github/workflows/main.yaml
          - .github/workflows/test.yaml
          - .github/workflows/pull_request.yaml
          - .github/workflows/wc-update-aqua-checksums.yaml
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}
