name: test
on: pull_request
  # push:
  #   paths:
  #     - .github/workflows/main.yaml
  #     - .github/workflows/test.yaml

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/main.yaml
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - aqua/aqua.yaml
          - aqua/imports/ghalint.yaml
          - ghalint.yaml
        renovate-config-validator:
          - renovate.json
          - .github/workflows/test.yaml
          - .github/workflows/wc-renovate-config-validator.yaml
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}

  test_aqua_config:
    permissions:
      contents: read
    uses: ./.github/workflows/main.yaml
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - .github/aqua/ci.yaml
          - .github/aqua/imports/ghalint.yaml
          - ghalint.yaml
        renovate-config-validator:
          - renovate.json
          - .github/workflows/main.yaml
          - .github/workflows/test.yaml
          - .github/workflows/wc-renovate-config-validator.yaml
        update-aqua-checksums:
          - .github/aqua/ci.yaml
          - .github/aqua/imports/*.yaml
          - .github/aqua/aqua-checksums.json
          - .github/workflows/main.yaml
          - .github/workflows/test.yaml
          - .github/workflows/wc-update-aqua-checksums.yaml
      aqua_config: .github/aqua/ci.yaml
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}