name: test
on: pull_request
  # push:
  #   paths:
  #     - .github/workflows/main.yaml
  #     - .github/workflows/test.yaml

jobs:
  job1:
    # permissions:
    #   contents: read
    uses: ./.github/workflows/main.yaml
    with:
      filters: |
        ghalint:
          - .github/workflows/*.yaml
          - aqua/aqua.yaml
          - aqua/imports/ghalint.yaml
          - ghalint.yaml