---
name: ghalint
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.60.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
          AQUA_GITHUB_TOKEN: ${{github.token}}